
<MainWidget>:
    orientation : 'vertical'
    ScoreLabel:
        size_hint : 1, None
        height : dp(100)
        text: "SCORE : " + str(root.score)

    FloatLayout:
        ClickMeButton:
            text: "click me ! "
            size_hint: None, None
            height: dp(100)
            width: dp(100)
            pos_hint : {'x':root.pos_x, 'y':root.pos_y}
            on_press: root.on_button_press()